### ISSUE TITLE
Step by step guide

### ISSUE THREAD

**Issue by onikage04** [liuyishengalan/ThinkPad-P52-Hackintosh-10.15.x#15]
Hi, 
I'm new to hackintosh and I really want to install MacOS on my thinkpad p52.
Can someone help me to find a good step by step guide to install hackintosh on my laptop?

I don't know how to use the files in this repository.

thanks.

**Comment by azbestpl** [comment]
https://youtu.be/XcOFR3y1m2s - very good guide
