### ISSUE TITLE
[General question] VoodooSMBus, and 5 finger 🖐️

### ISSUE THREAD

**Issue by martinandersen3d** [liuyishengalan/ThinkPad-P52-Hackintosh-10.15.x#17]
Hi.

I've installed this repo with succes. Only missing the Multi Touch Gestures.
The patch-links does not seem to work in "leo-labs" repo;

https://github.com/leo-labs/VoodooSMBus

I guess you might have the files working on your machine? Can you please include them somewhere and a description of how to install? 

And a big Thanks to your work ;-)

**Comment by liuyishengalan** [comment]
GO to the release tab, and download the latest version
