### ISSUE TITLE
Thunderbolt support

### ISSUE THREAD

**Issue by romainmeunier** [liuyishengalan/ThinkPad-P52-Hackintosh-10.15.x#19]
Hi there !

Everything works well on Catalina, except Thunderbolt
Which kext/driver have I to load for Thunderbolt support ?

**Comment by Truongtvat** [comment]
Hi @romainmeunier!

How about temperatures, fan speed, fan noise of your laptop?.
Are you using HWMonitor app?. Can you share about your fix!.

**Comment by liuyishengalan** [comment]
Try version 2.6.
and even if the thunderbolt works, the thunderbolt always display as no kext loaded.
It doesn't matter
