### ISSUE TITLE
How to install Mac OS to Thinkpad P52

### ISSUE THREAD

**Issue by duyndfx00384** [liuyishengalan/ThinkPad-P52-Hackintosh-10.15.x#2]
I user win10. How to make UBS Mac boot. I try use transmac and copy clover in efi folder but not working

**Comment by liuyishengalan** [comment]
Can you describe your issue in detail? do you mean the USB disk cannot be booted? or you can not boot from clover

**Comment by bpiljic** [comment]
I try use transmac and copy clover in efi folder but not working,  USB disk cannot be boot.

**Comment by liuyishengalan** [comment]
Have you disabled the secure boot in BIOS?

**Comment by bpiljic** [comment]
Yes I have and cannot boot.

**Comment by aitordaw** [comment]
I Was able to boot installer by deleting patched dsdts... I think it's a BIOS ver. Missmatch?
