### ISSUE TITLE
Dim screen on Intel card

### ISSUE THREAD

**Issue by azbestpl** [liuyishengalan/ThinkPad-P52-Hackintosh-10.15.x#21]
I don't have T580 with dedicated GPU, just the normal one but I noticed that your config gives me a dimmer screen than another config that I found (can share).

On another hand HDMI works fine and boot up time is greatly improved. Cheers for your work.

**Comment by liuyishengalan** [comment]
I noticed that your device is T580. I suggest you using https://github.com/CrazyPegasus/ThinkPad-T580-Hackintosh @CrazyPegasus, one of the contributors of EFI of P52. This bootloader is designed for T580 specifically.
