### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by c3o8k1g** [liuyishengalan/ThinkPad-P52-Hackintosh-10.15.x#22]
### **Original Post (now obsolete - [see Issue 29 for the current situation](https://github.com/liuyishengalan/ThinkPad-P52-P53-P72-P73-Hackintosh-10.15.x/issues/29)).**

First and foremost, thanks for the wonderful work you are doing!

I personally found it very useful to be able to deploy your EFI directly without to much trouble.

I was successfull in installing MacOS 10.15.2 to a ThinkPad P52 (20M9001KMZ - [Lenovo website](http://psref.lenovo.com/Detail/ThinkPad/ThinkPad_P52?M=20M9001KMZ)).

// EDIT: EFI version used 2.9. //

I do have some questions left.

**1**. Is it better to leave the kexts into the EFI partition or move them to /System/Library/Extensions? How to do that, manually or with some kind of software?

**2**. I’m having issues with the configuration of the TrackPad, in particular the TrackPoint, TrackPad and its top buttons work perfectly, but I am unable to make the TrackPad's lower buttons work like intended in a regular TrackPad. The left button only works for drag-and-drop, the others 2 seem to be disabled.

**3**. Battery / Power consumption: I noticed the “endurance” is quite reduced in MacOS compared to Windows. Is it normal, or do I have some settings to adjust?

**4**. I do have Windows installed in a separate NVME SSD. I cannot get Clover to remember the preferred drive (MacOS) when booting up. The MacOs drive is the 1st slot, windows is installed in the 2nd one (also confirmed in the BIOS). Clover list Windows before MacOS.

**5**. Is there any chance to make the system sleep when closing the lid (also via keyboard shortcuts or third-party software)? 
When in sleeping mode either due to inactivity or via the Menu bar - Sleep command, sometimes after around 10 to 20 minutes it wakes up without an input.
To wake, it's necessary to use the power button; pressing any key does not work.

**6**. Which is the best mode for sleep/hibernation? 0, 3 or 25 (sleep mode, safe sleep or hibernation resepctively; some sources also mention 27 and 29 as possible values)?

**7**. Can you please confirm that this wi-fi card works in the P52 (FRU: 04X6020 - PN: 20-200480 - BCM94352Z)?

**8**. Is it possible to disable the red-dot System status indicator on the monitor cover or is it tied in with the power button indicator (I know, black tape could do just fine, but...).

**9**. Do you think it's possible to use a USB(-A or -C) docking station as a USB hub, Ethernet, SD Card reader and HDMI port?

**10**. If point 9 does not work, would a USB(-A or -C) to HDMI work and a separate one for SD and another for Ethernet?

**11**. When an update is released, is it safe to install it directly via the System preferences utility?

**12**. When an update to your EFI folder is released, is it safe to replace the old one entirely (taking care to change the SMBIOS to my values)?

**13**. I suggest you publish a guide detailing the installation process. I know there are many online already, but a model-specific one would be really useful, especially with all the quirks of a hackintosh machine and considering which of the included .plist to use. I can provide a text-only version of the steps I followed if necessary.

Thanks again!
Best Regards,
c3o8k1g

**EDIT 1:**
**3**. Power consumption
I had the opportunity to closely monitor the temperature of the CPU.
It averaged 70°C with peaks of up to 90°C when under moderate load (less than 50% load).

**EDIT 2:**
**5**. Sleep
I just noticed that in order to wake the computer from "sleep", pressing any key or using the touchpad or external devices does not work. Instead the power button must be used.

**EDIT 3:**
**5**. Wake from sleep
After using the computer for some time, the only keyboard key that wakes the laptop from sleep is "fn".

**EDIT 4:**
Sorry for the very long message.

**Comment by martinandersen3d** [comment]
CPU Temp:
TJUNCTION 100°C

TJUNCTION
Junction Temperature is the maximum temperature allowed at the processor die.

**Everything under 100 is fine for your CPU**
https://ark.intel.com/content/www/us/en/ark/products/134899/intel-core-i7-8850h-processor-9m-cache-up-to-4-30-ghz.html

_I'm not related to this repo, just wanted to answer you CPU question._

**Comment by c3o8k1g** [comment]
> CPU Temp:
> TJUNCTION 100°C

Thanks for your message.
I know that very well.
The issue here is the relation between apparently high temperatures with low to moderate loads and short battery endurance.

**Comment by c3o8k1g** [comment]
Original Post (now obsolete - see above for the current situation).

First and foremost, thanks for the wonderful work you are doing!

I personally found it very useful to be able to deploy your EFI directly without to much trouble.

I was successfull in installing MacOS 10.15.2 to a ThinkPad P52 (20M9001KMZ - [Lenovo website](http://psref.lenovo.com/Detail/ThinkPad/ThinkPad_P52?M=20M9001KMZ)).

// EDIT: EFI version used 2.9. //

I do have some questions left.

**1**. Is it better to leave the kexts into the EFI partition or move them to /System/Library/Extensions? How to do that, manually or with some kind of software?

**2**. I’m having issues with the configuration of the TrackPad, in particular the TrackPoint, TrackPad and its top buttons work perfectly, but I am unable to make the TrackPad's lower buttons work like intended in a regular TrackPad. The left button only works for drag-and-drop, the others 2 seem to be disabled.

**3**. Battery / Power consumption: I noticed the “endurance” is quite reduced in MacOS compared to Windows. Is it normal, or do I have some settings to adjust?

**4**. I do have Windows installed in a separate NVME SSD. I cannot get Clover to remember the preferred drive (MacOS) when booting up. The MacOs drive is the 1st slot, windows is installed in the 2nd one (also confirmed in the BIOS). Clover list Windows before MacOS.

**5**. Is there any chance to make the system sleep when closing the lid (also via keyboard shortcuts or third-party software)? 
When in sleeping mode either due to inactivity or via the Menu bar - Sleep command, sometimes after around 10 to 20 minutes it wakes up without an input.
To wake, it's necessary to use the power button; pressing any key does not work.

**6**. Which is the best mode for sleep/hibernation? 0, 3 or 25 (sleep mode, safe sleep or hibernation resepctively; some sources also mention 27 and 29 as possible values)?

**7**. Can you please confirm that this wi-fi card works in the P52 (FRU: 04X6020 - PN: 20-200480 - BCM94352Z)?

**8**. Is it possible to disable the red-dot System status indicator on the monitor cover or is it tied in with the power button indicator (I know, black tape could do just fine, but...).

**9**. Do you think it's possible to use a USB(-A or -C) docking station as a USB hub, Ethernet, SD Card reader and HDMI port?

**10**. If point 9 does not work, would a USB(-A or -C) to HDMI work and a separate one for SD and another for Ethernet?

**11**. When an update is released, is it safe to install it directly via the System preferences utility?

**12**. When an update to your EFI folder is released, is it safe to replace the old one entirely (taking care to change the SMBIOS to my values)?

**13**. I suggest you publish a guide detailing the installation process. I know there are many online already, but a model-specific one would be really useful, especially with all the quirks of a hackintosh machine and considering which of the included .plist to use. I can provide a text-only version of the steps I followed if necessary.

Thanks again!
Best Regards,
c3o8k1g


**EDIT 1:**
**3**. Power consumption
I had the opportunity to closely monitor the temperature of the CPU.
It averaged 70°C with peaks of up to 90°C when under moderate load (less than 50% load).


**EDIT 2:**
**5**. Sleep
I just noticed that in order to wake the computer from "sleep", pressing any key or using the touchpad or external devices does not work. Instead the power button must be used.


**EDIT 3:**
**5**. Wake from sleep
After using the computer for some time, the only keyboard key that wakes the laptop from sleep is "fn".



**EDIT x:**
Sorry for the very long message.
