### ISSUE TITLE
Catalina installer on thinkpad P53s keep reboot at "13 minutes remaining"

### ISSUE THREAD

**Issue by htrung4** [liuyishengalan/ThinkPad-P52-Hackintosh-10.15.x#23]
Hello, do you have the problem at the phase 2 of installation on your thinkpad? 
I'm using vanilla guide (my EFI is here: https://www.mediafire.com/file/i3xzh9lnjpae9nj/EFI_Thinkpad_P53s.zip/file)

**Status**: disabled dGPU, patched HD620 (able to boot to the installation USB without fake ID)

**Problem**: I finished the first phase of installation (auto reboot at 2 minutes remaining); then I was able to boot to the new installed disk, but it keeps rebooting at "13 minutes remaining". The verbose as in the picture. Do you have any solution for this? 
Thank you and good day.

![P53s](https://user-images.githubusercontent.com/9250289/73298485-a8124880-420d-11ea-9e3a-87f06e548e37.jpg)

**Comment by liuyishengalan** [comment]
It is not for P53s, sorry about that
