### ISSUE TITLE
Thinkpad P73 stuck on boot

### ISSUE THREAD

**Issue by asalvi0** [liuyishengalan/ThinkPad-P52-Hackintosh-10.15.x#24]
**Thinkpad P73**
**Machine Type Model:** 20QRCTO1WW
**CPU**: 9750H
**Nvidia GPU**: Quadro P620

BIOS settings are set properly, booting to install loads normally, it works wih the 4K resolution:
![IMG_20200213_093432](https://user-images.githubusercontent.com/775410/74451429-3c52f100-4e45-11ea-8544-ebf65841dbaf.jpg)

after the apple logo loads completely it just get stuck with the following icon:
![IMG_20200213_093514](https://user-images.githubusercontent.com/775410/74451436-3eb54b00-4e45-11ea-9f49-c9fec20d4960.jpg)

**Comment by liuyishengalan** [comment]
Thanks for feedbacks
Are you in the progress on installing?
Try to use a USB 2.0 stick
Any issues please upload the image of -v (verbose) UI

**Comment by liuyishengalan** [comment]
it is likely due to the different ports defined on USB, You may use another port to install.
Good Luck

**Comment by asalvi0** [comment]
Here are the verbose outputs, I tried with all the ports both USB 2.0 and 3.1 sticks, also using the ZIP file from releases and files from source _(replacing config.plist file from the proper P73 4k folder)_:

Here the logs using the files taken from the repo source:
![IMG_20200215_104838](https://user-images.githubusercontent.com/775410/74593660-34d14a80-4ff3-11ea-8b0a-254c4af1ab98.jpg)


Here the logs using the files from the Release ZIP:
![IMG_20200215_124935](https://user-images.githubusercontent.com/775410/74593696-985b7800-4ff3-11ea-8cd8-18e41d60ae4b.jpg)

After both errors the prohibited sign appears and makes text unreadable.

**Comment by liuyishengalan** [comment]
Which nvme ssd do you use?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by asalvi0** [comment]
2x 256gb Opal SSD, no passwords or additional encryption enabled in BIOS:

![ssd](https://user-images.githubusercontent.com/775410/74593850-50d5eb80-4ff5-11ea-8916-aa2a02d79d31.PNG)

**Comment by liuyishengalan** [comment]
Samsung one should be pm981a. It's not compatible on macos. Did you install on this drive?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by asalvi0** [comment]
I used a Samsung & ADATA USB drives, got same errors with both. I haven't even got to the installation screen, I'm trying to boot to the installer.

**Comment by AlexVKO** [comment]
@asalvi0 you did it? I'm thinking on buying this laptop
