### ISSUE TITLE
can support P70 ?

### ISSUE THREAD

**Issue by CMingTseng** [liuyishengalan/ThinkPad-P52-Hackintosh-10.15.x#30]
Dear Sir

the EFI can support P70 ?

THX

**Comment by c3o8k1g** [comment]
Probably not. P50/P51s (and P70/P71s) have a different architecture compared to P52/P53s (and P72/P73s).
Better leave a more definitive answer to the author @liuyishengalan though.

**Comment by liuyishengalan** [comment]
Exactly no, these models are totally different, including the chipset, integrated GPU, and USB ports definitions.
