### ISSUE TITLE
DSDT Missmatch Booting issues and reboots to splash screen

### ISSUE THREAD

**Issue by aitordaw** [liuyishengalan/ThinkPad-P52-Hackintosh-10.15.x#6]
My P52 has 8850H and P2000 quadro, this is my DSDT origin files. Can you patch and aupdate with both, please?

Thank you for your job!

https://mega.nz/#!NBVm0SKS!HdDttTWb_q_BbfyawVvATWKdQC1PpWWfDM_SISRRKPs

**Comment by liuyishengalan** [comment]
Now, all models have been supported. THX for comment
