### ISSUE TITLE
Xeon E-2176M Supported?

### ISSUE THREAD

**Issue by BrianPuccio** [liuyishengalan/ThinkPad-P52-Hackintosh-10.15.x#7]
Thanks for putting this all together in one place, super useful!

Do you know if this would be equally compatible with a P52 that was configured with a Xeon E-2176M CPU?

**Comment by liuyishengalan** [comment]
Exactly, by using the new updated hotpatch version EFI

**Comment by BrianPuccio** [comment]
Thanks!
