### ISSUE TITLE
关于屏幕亮度控制，请问是处理的？

### ISSUE THREAD

**Issue by YoWenhow** [liuyishengalan/ThinkPad-P52-Hackintosh-10.15.x#8]
我在你的pathed文件夹中看到ssdt-kbd.aml文件，在maciasl中打开似乎是修复了键盘控制，如果我直接拿来用需要配合其他驱动么，dsdt还需要在path键盘相关的配置么，VoodooPS2Controller.kext是不是就足够了。

**Comment by liuyishengalan** [comment]
键盘fn 是宪武的方案
